apiVersion: v1
kind: ConfigMap
metadata:
  name: library-config
data:
  APP_ENV: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: library-system
  template:
    metadata:
      labels:
        app: library-system
    spec:
      containers:
        - name: library-container
          image: library-system:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: library-config
---
apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  selector:
    app: library-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: library-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: library.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: library-service
                port:
                  number: 80
